@startuml
start
repeat 
    :Система предлагает пользователю зарегистрироваться или войти;
    :Система проверяет учетные данные;
repeat while (Данные валидны?) is (Нет);

:Выполняется вход в систему;
:Клиент выбирает товары и добавляет их в корзину;
:Клиент выбирает способ оплаты;
:Клиент вводит промокод;
:Клиент оформляет заказ;
fork
    if (Товар в наличии?) is (Нет) then
        :Клиенту предлагается альтернативный товар; 
        if (Клиент выбрал замену товара или удалил отсутствующий товар?) is (Нет) then
            #Ivory: Заказ переходит в статус "Ожидание поступления товара";
            :Уведомление клиента о статусе заказа с информацией об отсутствии товаров;
        stop
        else (Да)
        endif
    else (Да)
    endif

fork again
    if (Промокод введен?) is (Да) then
        if (Превышен лимит на использование промокода?) is (Да) then
            :Уведомление клиента о превышении лимита на использование промокода;
        else (Нет)
            if (Промокод действует на выбранные товары?) is (Нет) then
            :Уведомление клиента о том, что промокод не действует;
            else (Да)
            :Обновление цены с учетом скидки по промокоду;
            :Уведомление клиента о том, что промокод применен;
            endif
        endif  
    else (Нет)
    endif

end fork

#Ivory: Заказ переходит в статус "Отправлен";
:Уведомление клиента о статусе заказа;
fork
    :Система уведомляет склад о необходимости собрать заказ;
    :Сотрудники склада комплектуют заказ;
    #Ivory: Заказ переходит в статус "Собран и ожидает оплаты";
    :Уведомление клиента о статусе заказа;

fork again
    :Система проверяет платежные данные;
end fork

repeat :Система производит транзакцию;
if (Платеж удачен?) then (Да)
    break
else (Нет)
:Уведомление клиента о причине неудачной оплаты 
(Недостаточно средсв, платежная система недоступна ит.п.);
    if (Повторить попытку оплаты?) then (Нет)
        if (Изменить способ оплаты?) is (Нет) then
            #pink: Заказ переходит в статус "Отменен из-за проблем с оплатой";
             :Уведомление клиента о статусе заказа;
            stop
        else (Да)           
        endif
    else (Да)   
    endif

    if (Это вторая попытка текущего способа оплаты?) is (Да) then
    #pink: Заказ переходит в статус "Отменен из-за проблем с оплатой";
    :Уведомление клиента о статусе заказа;
    stop
    else (Нет)
    endif

endif   


repeat while (Все еще не проходит оплата?) is (Да);

: Генерация счет-фактуры;
#PaleGreen: Заказ переходит в статус "Отправлен";
: Уведомление клиента о статусе заказа;
stop
@enduml