@startuml 
class Customer {
- name: String
- email: String
+ placeOrder(): void
}
class Order {
- orderld: int
- date: Date
+ calculate Total(): double
}

class PremiumCustomer { 
+ getRewards(): void
}

Customer "1" -- "O..*" Order: 
places
Customer <|-- PremiumCustomer 
@enduml