@startuml
actor Покупатель  as C 
participant "Интерфейс сайта магазина" as UI
participant "Контроллер обработки заказов" as OC
participant "Платежный сервис" as PS
database "База данных" as DB
C-> UI: Запрос на оформление заказа (детали заказа)
UI-> OC: Передача данных заказа (детали заказа)
OC -> DB: Сохранение заказа (детали заказа)
DB --> OC: Результат сохранения заказа
OC -> PS: Проведение платежа (информация о платеже)
PS --> OC: Результат платежа
OC --> UI: Подтверждение заказа (детали подтверждения)
UI --> C: Информирование покупателя (детали подтверждения)
@enduml