@startuml 
state "Жизненный цикл банковской карты" as Card {
[*] --> Неактивная : Выпуск_карты
Неактивная --> Активная
state Активная {
[*] --> Обычная
[*] --> Премиум 
Премиум --> Обычная: [Понижение статуса клиента]
Обычная --> Премиум: [Повышение статуса клиента] 
||
[*] --> Заблокированная: [Подозрение на мошенничество]
Заблокированная --> Разблокированная: [Мошенничество опровергнуто]
||
[*] --> Утерянная: [Утеря карты]
Утерянная --> Найденная: [Карта найдена]
}
Активная --> Просроченная: [Таймаут. Истек срок действия]
Просроченная --> [*]
note left of Просроченная 
Автоматический переход в статус Просроченная по истечению срока дейсвия карты 
end note
}

@enduml
